# Generated by Django 3.2 on 2021-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
