# Generated by Django 3.2 on 2021-04-27 18:58

import cyber_report_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cyber_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('nature_of_crime', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('evidence_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('evidence_vid', models.FileField(blank=True, null=True, upload_to='', validators=[cyber_report_app.models.file_size])),
            ],
        ),
    ]
