# Generated by Django 3.2 on 2021-05-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_report_app', '0002_cyber_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyber_report',
            name='status',
            field=models.CharField(blank=True, default='Waiting', max_length=21, null=True),
        ),
    ]
