# Generated by Django 3.2 on 2021-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_report', '0003_auto_20210501_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime_report',
            name='status',
            field=models.CharField(default='Waiting', max_length=15),
        ),
    ]
