# Generated by Django 3.2 on 2021-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_report', '0004_crime_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_report',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Under Investigation', 'Under Investigation'), ('Solved', 'Solved')], default='Waiting', max_length=21),
        ),
    ]
