# Generated by Django 3.2 on 2021-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_report', '0007_alter_crime_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_report',
            name='status',
            field=models.CharField(blank=True, default='Waiting', max_length=21, null=True),
        ),
    ]
